### PR TITLE
General Update for 64-bit build and Portability 

### PR DESCRIPTION
**Pull request by QwazyWabbitWOS**
These updates add some portability for FreeBSD and GNU Linux makefiles.
Deletes Win32 Alpha build options from Visual Studio solution file.
Defaults to 64-bit builds on Linux, uncomment the #ARCH=i386 
at line 6 of GNUmakefile to get 32-bit build.
BSDmakefile may need modification.

### CODE REVIEW

**Comment by tastyspleen** [comment]
Thanks!

(N.B. We still build i386 on tastyspleen, due to the number of binary-only Q2 mods for which source code was never available.)

**Comment by QwazyWabbitWOS** [comment]
You're welcome!
I knew there would need to be a backward compatibility and I knew there were a few coders out there doing 64-bit builds. Pull the changes and uncomment the ARCH = i386 in your repo and push if you wish to default to 32-bit on your fork. I thought it would be best to have the changes documented in more than one place but I suppose if GitHub disappears they all disappear.

QW

**Comment by tastyspleen** [comment]
Merged commits as-is. Since the makefile now determines arch based on uname, I'm able to use `/usr/bin/setarch` to build for i386, as follows:

`setarch i386 make -f GNUmakefile`

**Comment by QwazyWabbitWOS** [comment]
I like that much better than hacking the makefile. I'll document it in the makefile on the next push to my fork. I'm still a newb on Linux command line stuff like that so it never occurs to me to do that. Focused on make's quirks is bad enough some days. BTW, Linux uses GNUmakefile automatically and BSD defaults to BSDmakefile so you can eliminate the -f GNUmakefile and just do the `setarch i386 make all ` and it will rebuild the 32-bit dll even after a 64-bit build.

**Pull request merged**
